version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: djangorestframework
    versions:
    - 3.12.2
  - dependency-name: markdown
    versions:
    - 3.3.3
  - dependency-name: gunicorn
    versions:
    - 20.0.4
