# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ckcer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckcer',
            name='company',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
