# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
