# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('number', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='myuser',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Division'),
        ),
    ]
