# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180710_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
