# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180712_2202'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([('name', 'number')]),
        ),
    ]
