# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180713_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
