# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180714_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tag'),
        ),
    ]
