# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180716_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='division',
            name='number',
            field=models.CharField(max_length=1),
        ),
    ]
