# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180717_0233'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set([]),
        ),
    ]
