# Generated by Django 2.1.2 on 2018-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20181105_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
    ]
