# Generated by Django 2.1.2 on 2018-11-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('api', '0017_remove_myuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country'),
        ),
    ]
